### ISSUE TITLE
Misuse of ruby class variable

### ISSUE THREAD

**Issue by Deradon** [alexdovzhanyn/rydux#1]
I saw in your readme following:

```
require 'rydux'

class UserReducer < Rydux::Reducer
  @@initial_state = { name: 'Alex', age: 20 }

  def self.map_state(action, state = @@initial_state)
```

I **strongly** suggest not to use class variable here as they have unexpected side effects.
In ruby, class variable (`@@class_var`) are shared across all subclasses!

## Minimal Example

If for whatever reason the parent class also declares the same class variable you'll get some unexpected behavior.

```
class Abstract
  @@class_var = :Abstract
end

class Foo < Abstract
  @@class_var = :Foo

  attr_reader :name

  def initialize(name: @@class_var)
    @name = name
  end
end

class Bar < Abstract
  @@class_var = :Bar
end

Foo.new.name
# => :Bar
```

So I'd suggest to use a constant here:

```
require 'rydux'

class UserReducer < Rydux::Reducer
  INITIAL_STATE = { name: 'Alex', age: 20 }

  # If you don't want to make the constant available outside of this class
  # private_constant :INITIAL_STATE

  def self.map_state(action, state = INITIAL_STATE)
```

**Comment by alexdovzhanyn** [comment]
I understand the concern, but it depends on the usage, actually. Class variables are shared by all "class instances" (i.e. subclasses), but if you never intend to extend your class, the difference is purely  aesthetic. The Reducer class in rydux is treated as a singleton and so it never gets initialized, its meant to encapsulate all code relating to whatever reducer is extending it, so in this case the use of the class variable is fine, it truly is storing a variable that is relevant to the entire class
