### ISSUE TITLE
How do you combine reducers?

### ISSUE THREAD

**Issue by ChrisVilches** [alexdovzhanyn/rydux#3]
Is it possible to combine many reducers into one?

If so, can you please provide an example?

**Comment by ChrisVilches** [comment]
Oh, is it like this?

```ruby
Store = Rydux::Store.new(user: UserReducer, another: AnotherReducer, etc: EtcReducer)
```

**Comment by alexdovzhanyn** [comment]
@FeloVilches Yep, exactly. I'm using Rydux heavily in https://github.com/alexdovzhanyn/SevenDeadlySinsRevamp, so that should be a good reference. Here's how I'm combining reducers in that codebase:

```ruby
Store = Rydux::Store.new(game: GameReducer, player: PlayerReducer, camera: CameraReducer)
```
